content:
  - name: docs
    label: Docs
    path: docs/⚙️ Оптимизация сервера
    type: collection
    filename: "{primary}.md"
    fields:
      - { name: title, label: title, type: string}
      - { name: id, label: ID, type: string}
      - { name: body, label: Body, hidden: true, type: rich-text}